name: Bandit

on:
    push:
        branches:
            - sast

jobs:
    analyze:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v3
              with:
                  python-version: 3.9

            - name: Install Bandit
              run: pip install bandit

            - name: Run Bandit Scan
              run: bandit -r . --exit-zero -c bandit.yaml # -f json -o bandit-report.json
